//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergTestUebungen.DatenBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class myorders
    {
        public long ordid { get; set; }
        public long custid { get; set; }
        public Nullable<long> empid { get; set; }
        public System.DateTime orderdate { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
